# Available profiles for dotfiles installation
profiles:
  default:
    description: Default profile for Coder workspaces with development tools
    include_defaults: true
    features:
      - claude marketplace configuration
    tools:
      - node (via mise)
      - npm (via mise)
    packages:
      - none (Claude Code should be installed separately)

  onXmaps:
    description: onXmaps profile for Coder workspaces with development tools
    include_defaults: true
    features:
      - claude marketplace configuration
    tools:
      - node (via mise)
      - npm (via mise)
    packages:
      - none (Claude Code should be installed separately)