# Available profiles for dotfiles installation
profiles:
  default:
    description: Default profile for Coder workspaces with development tools
    include_defaults: true
    features:
      - claude
    tools:
      - node (via mise)
      - npm (via mise)
    packages:
      - "@anthropic-ai/claude-code" (global npm)

  onXmaps:
    description: onXmaps profile for Coder workspaces with development tools
    include_defaults: true
    features:
      - claude
    tools:
      - node (via mise)
      - npm (via mise)
    packages:
      - "@anthropic-ai/claude-code" (global npm)