name: Test Dotfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run dotfiles tests
        run: |
          chmod +x test/test-dotfiles.sh
          ./test/test-dotfiles.sh
